In [44]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("C:\\Users\\madie\\mcm-2022\\powerprofile.csv")
df.head()

,Unnamed: 0,id,age,gender,activities,bike,run,swim,other,1s_critical_power,...,30m_critical_power,1m_peak_wpk,5m_peak_wpk,10m_peak_wpk,20m_peak_wpk,30m_peak_wpk,Unnamed: 22,W,CP,Pmax
0,1,9bdd724b-4148-4bee-9344-9e7a526c7fc1,36,M,21,21,0,0,0,681.0,...,223.83444,5.09851,4.26751,3.92614,3.44220,3.34081,NaN,20789.815591,216.662902,681.0
1,2,f43673fa-600b-4b0b-8c3a-ef627347ebe1,46,M,227,3,78,14,132,599.0,...,237.47556,4.73721,3.69107,3.64966,3.55519,3.45198,NaN,4518.083450,241.429537,599.0
2,5,f81b4144-4805-4086-a516-9e348a702e91,55,M,276,276,0,0,0,943.0,...,235.00389,6.38254,4.36741,4.15061,3.87675,3.73022,NaN,16537.945257,231.196836,943.0
3,6,34d0b9f3-3952-4bab-aa8b-b8d84f966192,37,M,654,567,34,0,53,1162.0,...,240.89222,8.24062,5.38627,4.61097,4.07310,4.04861,NaN,23140.158462,224.960315,1162.0
4,7,025bad5c-1cfc-4c22-a2e3-2be1ccb70008,42,M,1632,1083,542,3,4,1212.0,...,323.98111,5.76245,5.46764,5.31485,5.25997,5.25943,NaN,4943.963165,319.792339,1212.0

In [4]:
df.columns

Index(['Unnamed: 0', 'id', 'age', 'gender', 'activities', 'bike', 'run',
       'swim', 'other', '1s_critical_power', '15s_critical_power',
       '2m_critical_power', '3m_critical_power', '5m_critical_power',
       '8m_critical_power', '10m_critical_power', '20m_critical_power',
       '30m_critical_power', '1m_peak_wpk', '5m_peak_wpk', '10m_peak_wpk',
       '20m_peak_wpk', '30m_peak_wpk', 'Unnamed: 22', 'W', 'CP', 'Pmax'],
      dtype='object')

In [5]:
cp = df[['1s_critical_power', '15s_critical_power',
       '2m_critical_power', '3m_critical_power', '5m_critical_power',
       '8m_critical_power', '10m_critical_power', '20m_critical_power',
       '30m_critical_power']]

In [10]:
cp = cp.transpose()

In [11]:
cp.head()

,0,1,2,3,4,5,6,7,8,9,...,846,847,848,849,850,851,852,853,854,855
1s_critical_power,681.00000,599.00000,943.00000,1162.00000,1212.00000,1205.00000,1615.00000,1154.00000,901.00000,1505.00000,...,976.00000,952.00000,2034.00000,778.00000,809.00000,2000.00000,2000.00000,1091.00000,1072.00000,793.00000
15s_critical_power,500.13333,562.60000,698.53333,793.40000,541.06667,895.60000,889.00000,1036.86667,860.26667,566.09731,...,688.26667,856.86667,965.80000,602.80000,697.86667,1187.05800,814.10509,765.86667,583.20000,667.93333
2m_critical_power,302.20000,273.13333,348.61667,371.06667,351.04167,426.12500,391.60000,394.06667,361.15000,289.63333,...,350.80833,421.32968,457.71667,343.67500,372.20000,417.85833,402.75484,398.24167,279.36667,364.51667
3m_critical_power,294.05000,259.45000,314.81667,331.48889,348.03889,382.83889,370.06111,356.51111,346.44444,268.95556,...,336.05833,395.08647,391.33333,310.63889,365.99444,400.45000,368.72222,357.57778,270.10000,344.57778
5m_critical_power,285.92333,258.35667,275.14667,315.09667,336.80667,347.72167,339.99667,315.62833,338.00333,252.59333,...,289.53933,353.09860,357.52333,294.89000,360.87333,350.93333,348.28333,321.81667,266.52000,315.83667

In [12]:
cp["t"] = [1,15,120,180,300,480,600,1200,1800]

In [31]:
cp

In [13]:
cp.head(100)

,0,1,2,3,4,5,6,7,8,9,...,847,848,849,850,851,852,853,854,855,t
1s_critical_power,681.00000,599.00000,943.00000,1162.00000,1212.00000,1205.00000,1615.00000,1154.00000,901.00000,1505.00000,...,952.00000,2034.00000,778.00000,809.00000,2000.00000,2000.00000,1091.00000,1072.00000,793.00000,1
15s_critical_power,500.13333,562.60000,698.53333,793.40000,541.06667,895.60000,889.00000,1036.86667,860.26667,566.09731,...,856.86667,965.80000,602.80000,697.86667,1187.05800,814.10509,765.86667,583.20000,667.93333,15
2m_critical_power,302.20000,273.13333,348.61667,371.06667,351.04167,426.12500,391.60000,394.06667,361.15000,289.63333,...,421.32968,457.71667,343.67500,372.20000,417.85833,402.75484,398.24167,279.36667,364.51667,120
3m_critical_power,294.05000,259.45000,314.81667,331.48889,348.03889,382.83889,370.06111,356.51111,346.44444,268.95556,...,395.08647,391.33333,310.63889,365.99444,400.45000,368.72222,357.57778,270.10000,344.57778,180
5m_critical_power,285.92333,258.35667,275.14667,315.09667,336.80667,347.72167,339.99667,315.62833,338.00333,252.59333,...,353.09860,357.52333,294.89000,360.87333,350.93333,348.28333,321.81667,266.52000,315.83667,300
8m_critical_power,267.99375,252.40000,267.19583,278.39792,330.34167,312.18854,322.75000,306.59479,321.54583,236.26250,...,323.61235,326.23542,287.07917,328.68750,299.62332,316.96875,303.59792,246.10208,302.49167,480
10m_critical_power,263.05167,251.07500,261.48833,269.74167,327.39500,307.20417,300.69667,293.54333,308.90667,233.95000,...,310.68715,323.43167,285.15667,318.12833,293.08533,310.15333,293.90167,223.51500,296.19000,600
20m_critical_power,230.62750,244.57583,244.23500,242.34917,324.01417,291.12375,290.31333,277.47375,284.86583,224.60917,...,281.41250,288.30583,248.20300,302.01208,256.39495,291.55417,275.77917,192.51500,277.71667,1200
30m_critical_power,223.83444,237.47556,235.00389,240.89222,323.98111,270.94417,263.78806,264.79222,273.70556,217.01389,...,268.76020,270.59778,245.18389,288.23694,248.21108,273.97167,253.04000,177.06444,241.40556,1800

In [26]:
cp.columns = cp.columns.str.lstrip('0')

In [27]:
print(cp.columns)

Index([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       ...
       nan, nan, nan, nan, nan, nan, nan, nan, nan, 't'],
      dtype='object', length=857)

In [ ]:
# Functions for hyperbolic axis scaling
f = lambda x: 1/x
fig = plt.figure()
ax = plt.gca()
x = cp["t"]
y = cp.iloc[:,0]
plt.scatter(x,y)
#plt.xscale("function",functions=(f,f))
#plt.xticks([-22,-15,0,1,0.5])
plt.xticks(np.arange(0,1800,step=100))

plt.show()